const fs = require('fs');
const path = require('path');
const vm = require('vm');

const srcDir = 'C:\\Users\\O1004\\.gemini\\antigravity\\scratch\\jlpt-n5-textbook';
const n5File = path.join(srcDir, 'data_n5.js');

const megaWordsPt2 = [
  // ================= 飲食文化 (food_culture) Part 2 =================
  { id: "v_f_ebi", word: "海老", furigana: "えび", romaji: "ebi", meaning: "蝦子", level: "N4", category: "food_culture",
    sentences: [{ ja: "エビの天ぷらが好きです。", furigana: "えびのてんぷらがすきです。", en: "喜歡炸蝦天婦羅。" }] },
  { id: "v_f_kani", word: "蟹", furigana: "かに", romaji: "kani", meaning: "螃蟹", level: "N4", category: "food_culture",
    sentences: [{ ja: "冬はカニ鍋が美味しいです。", furigana: "ふゆはカニなべがおいしいです。", en: "冬天的螃蟹鍋很好吃。" }] },
  { id: "v_f_toufu", word: "豆腐", furigana: "とうふ", romaji: "toufu", meaning: "豆腐", level: "N4", category: "food_culture",
    sentences: [{ ja: "味噌汁に豆腐を入れます。", furigana: "みそしるにとうふをいれます。", en: "把豆腐加進味噌湯裡。" }] },
  { id: "v_f_nattou", word: "納豆", furigana: "なっとう", romaji: "nattou", meaning: "納豆", level: "N4", category: "food_culture",
    sentences: [{ ja: "納豆は健康にとてもいいです。", furigana: "なっとうはけんこうにとてもいいです。", en: "納豆對健康非常好。" }] },
  { id: "v_f_chiizu", word: "チーズ", furigana: "ちーず", romaji: "chiizu", meaning: "起司", level: "N5", category: "food_culture",
    sentences: [{ ja: "ピザにチーズをたっぷりのせます。", furigana: "ぴざにちーずをたっぷりのせます。", en: "在披薩上放滿起司。" }] },
  { id: "v_f_bataa", word: "バター", furigana: "ばたー", romaji: "bataa", meaning: "奶油", level: "N5", category: "food_culture",
    sentences: [{ ja: "パンにバターを塗って食べます。", furigana: "ぱんにばたーをぬってたべます。", en: "把奶油塗在麵包上吃。" }] },
  { id: "v_f_koshou", word: "胡椒", furigana: "こしょう", romaji: "koshou", meaning: "胡椒", level: "N4", category: "food_culture",
    sentences: [{ ja: "肉に塩と胡椒をかけます。", furigana: "にくにしおとこしょうをかけます。", en: "在肉上撒鹽和胡椒。" }] },
  { id: "v_f_su", word: "酢", furigana: "す", romaji: "su", meaning: "醋", level: "N4", category: "food_culture",
    sentences: [{ ja: "料理に少しお酢を加えます。", furigana: "りょうりにすこしおすをくわえます。", en: "在料理中加一點醋。" }] },
  { id: "v_f_mayoneezu", word: "マヨネーズ", furigana: "まよねーず", romaji: "mayoneezu", meaning: "美乃滋", level: "N4", category: "food_culture",
    sentences: [{ ja: "サラダにマヨネーズをかけます。", furigana: "さらだにまよねーずをかけます。", en: "在沙拉上淋美乃滋。" }] },
  { id: "v_f_jamu", word: "ジャム", furigana: "じゃむ", romaji: "jamu", meaning: "果醬", level: "N5", category: "food_culture",
    sentences: [{ ja: "いちごジャムをパンに塗ります。", furigana: "いちごじゃむをぱんにぬります。", en: "把草莓果醬塗在麵包上。" }] },
  { id: "v_f_tansansui", word: "炭酸水", furigana: "たんさんすい", romaji: "tansansui", meaning: "碳酸水 / 氣泡水", level: "N3", category: "food_culture",
    sentences: [{ ja: "炭酸水を飲むとすっきりします。", furigana: "たんさんすいをのむとすっきりします。", en: "喝氣泡水會覺得很清爽。" }] },
  { id: "v_f_musu", word: "蒸す", furigana: "むす", romaji: "musu", meaning: "蒸", level: "N3", category: "food_culture",
    sentences: [{ ja: "魚を野菜と一緒に蒸します。", furigana: "さかなをやさいといっしょにむします。", en: "把魚和蔬菜一起蒸。" }] },
  { id: "v_f_itameru", word: "炒める", furigana: "いためる", romaji: "itameru", meaning: "炒", level: "N3", category: "food_culture",
    sentences: [{ ja: "豚肉とキャベツを炒めます。", furigana: "ぶたにくときゃべつをいためます。", en: "炒豬肉和高麗菜。" }] },
  { id: "v_f_nuru", word: "塗る", furigana: "ぬる", romaji: "nuru", meaning: "塗抹", level: "N4", category: "food_culture",
    sentences: [{ ja: "パンにバターを塗ります。", furigana: "ぱんにばたーをぬります。", en: "在麵包上塗奶油。" }] },
  { id: "v_f_shiboru", word: "絞る", furigana: "しぼる", romaji: "shiboru", meaning: "擠(汁)", level: "N3", category: "food_culture",
    sentences: [{ ja: "唐揚げにレモンを絞ります。", furigana: "からあげにれもんをしぼります。", en: "在炸雞上擠檸檬汁。" }] },
  { id: "v_f_hanbaagu", word: "ハンバーグ", furigana: "はんばーぐ", romaji: "hanbaagu", meaning: "漢堡排", level: "N5", category: "food_culture",
    sentences: [{ ja: "子供はハンバーグが大好きです。", furigana: "こどもははんばーぐがだいすきです。", en: "小孩子最喜歡漢堡排。" }] },
  { id: "v_f_sandoitchi", word: "サンドイッチ", furigana: "さんどいっち", romaji: "sandoitchi", meaning: "三明治", level: "N5", category: "food_culture",
    sentences: [{ ja: "昼ご飯はコンビニのサンドイッチでした。", furigana: "ひるごはんはこんびにのさんどいっちでした。", en: "午餐吃便利商店的三明治。" }] },
  { id: "v_f_gyouza", word: "餃子", furigana: "ぎょうざ", romaji: "gyouza", meaning: "餃子", level: "N4", category: "food_culture",
    sentences: [{ ja: "ラーメンと一緒に餃子を頼みます。", furigana: "らーめんといっしょにぎょうざをたのみます。", en: "點拉麵順便點了餃子。" }] },
  { id: "v_f_gyuudon", word: "牛丼", furigana: "ぎゅうどん", romaji: "gyuudon", meaning: "牛丼", level: "N5", category: "food_culture",
    sentences: [{ ja: "安くて美味しい牛丼を食べます。", furigana: "やすくでおいしいぎゅうどんをたべます。", en: "吃便宜又好吃的牛丼。" }] },
  { id: "v_f_teishoku", word: "定食", furigana: "ていしょく", romaji: "teishoku", meaning: "定食 / 套餐", level: "N4", category: "food_culture",
    sentences: [{ ja: "食堂で焼き魚定食を注文しました。", furigana: "しょくどうでやきざかなていしょくをちゅうもんしました。", en: "在食堂點了烤魚套餐。" }] },
  { id: "v_f_oshibori", word: "おしぼり", furigana: "おしぼり", romaji: "oshibori", meaning: "濕紙巾", level: "N4", category: "food_culture",
    sentences: [{ ja: "レストランに入ると、おしぼりが出ます。", furigana: "れすとらんにはいると、おしぼりででます。", en: "進餐廳會送上濕紙巾。" }] },
  { id: "v_f_torizara", word: "取り皿", furigana: "とりざら", romaji: "torizara", meaning: "分食盤", level: "N3", category: "food_culture",
    sentences: [{ ja: "すみません、取り皿を三枚ください。", furigana: "すみません、とりざらをさんまいくてください。", en: "不好意思，請給我三個分食用的盤子。" }] },
  { id: "v_f_mochikaeri", word: "持ち帰り", furigana: "もちかえり", romaji: "mochikaeri", meaning: "外帶", level: "N4", category: "food_culture",
    sentences: [{ ja: "このピザは持ち帰りにします。", furigana: "このぴざはもちかえりにします。", en: "這個披薩要外帶。" }] },

  // ================= 服飾與美容 (fashion_beauty) Part 2 =================
  { id: "v_c_wanpiisu", word: "ワンピース", furigana: "わんぴーす", romaji: "wanpiisu", meaning: "連身裙", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "夏は涼しいワンピースを着ます。", furigana: "なつはすずしいわんぴーすをきます。", en: "夏天穿涼爽的連身裙。" }] },
  { id: "v_c_sangurasu", word: "サングラス", furigana: "さんぐらす", romaji: "sangurasu", meaning: "太陽眼鏡", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "海へ行く時はサングラスをかけます。", furigana: "うみへいくときはさんぐらすをかけます。", en: "去海邊時會戴太陽眼鏡。" }] },
  { id: "v_c_sandaru", word: "サンダル", furigana: "さんだる", romaji: "sandaru", meaning: "涼鞋", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "夏はサンダルを履いて出かけます。", furigana: "なつはさんだるをはいてでかけます。", en: "夏天穿涼鞋出門。" }] },
  { id: "v_c_buutsu", word: "ブーツ", furigana: "ぶーつ", romaji: "buutsu", meaning: "靴子", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "冬は暖かいブーツを履きます。", furigana: "ふゆはあたたかいぶーつをはきます。", en: "冬天穿保暖的靴子。" }] },
  { id: "v_c_sengannryou", word: "洗顔料", furigana: "せんがんりょう", romaji: "senganryou", meaning: "洗面乳", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "新しい洗顔料を買いました。", furigana: "あたらしいせんがんりょうをかいました。", en: "買了新的洗面乳。" }] },
  { id: "v_c_keshousui", word: "化粧水", furigana: "けしょうすい", romaji: "keshousui", meaning: "化妝水", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "顔を洗った後、化粧水をつけます。", furigana: "かおをあらったあと、けしょうすいをつけます。", en: "洗完臉後擦化妝水。" }] },
  { id: "v_c_hiyakedome", word: "日焼け止め", furigana: "ひやけどめ", romaji: "hiyakedome", meaning: "防曬乳", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "外に出る前に日焼け止めを塗ります。", furigana: "そとにでるまえにひやけどめをぬります。", en: "出門前會塗防曬乳。" }] },
  { id: "v_c_shanpuu", word: "シャンプー", furigana: "しゃんぷー", romaji: "shanpuu", meaning: "洗髮精", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "いい匂いのシャンプーを使っています。", furigana: "いいにおいのしゃんぷーをつかっています。", en: "使用好聞的洗髮精。" }] },
  { id: "v_c_sekken", word: "石鹸", furigana: "せっけん", romaji: "sekken", meaning: "肥皂", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "石鹸で手をきれいに洗います。", furigana: "せっけんでてをきれいにあらいます。", en: "用肥皂把手洗乾淨。" }] },
  { id: "v_c_haburashi", word: "歯ブラシ", furigana: "はぶらし", romaji: "haburashi", meaning: "牙刷", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "旅行に歯ブラシを持っていきます。", furigana: "りょこうにはぶらしをもっていきます。", en: "帶牙刷去旅行。" }] },
  { id: "v_c_taoru", word: "タオル", furigana: "たおる", romaji: "taoru", meaning: "毛巾", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "顔を洗って、タオルで拭きます。", furigana: "かおをあらって、たおるでふきます。", en: "洗完臉後用毛巾擦乾。" }] },
  { id: "v_c_gara", word: "柄", furigana: "がら", romaji: "gara", meaning: "花色 / 圖案", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "このシャツの柄がとても好きです。", furigana: "このしゃつのがらがとてもすきです。", en: "我很喜歡這件襯衫的花色。" }] },
  { id: "v_c_muji", word: "無地", furigana: "むじ", romaji: "muji", meaning: "素色", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "仕事の時は無地のシャツを着ます。", furigana: "しごとのときはむじのしゃつをきます。", en: "上班時穿素色的襯衫。" }] },
  { id: "v_c_kitsui", word: "きつい", furigana: "きつい", romaji: "kitsui", meaning: "緊的 / 辛苦的", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "太ったので、ズボンがきつくなりました。", furigana: "ふとったので、ずぼんがきつくなりました。", en: "變胖了所以褲子變緊了。" }] },
  { id: "v_c_yurui", word: "ゆるい", furigana: "ゆるい", romaji: "yurui", meaning: "鬆的", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "この靴は少しゆるいです。", furigana: "このくつはすこしゆるいです。", en: "這雙鞋有點鬆。" }] },
  { id: "v_c_pittari", word: "ぴったり", furigana: "ぴったり", romaji: "pittari", meaning: "剛剛好 / 合身", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "この服のサイズはぴったりです。", furigana: "このふくのさいずはぴったりです。", en: "這件衣服的尺寸剛剛好。" }] },

  // ================= 居住與家電 (housing_space) Part 2 =================
  { id: "v_h_senmenjo", word: "洗面所", furigana: "せんめんじょ", romaji: "senmenjo", meaning: "洗臉台 / 盥洗室", level: "N4", category: "housing_space",
    sentences: [{ ja: "朝起きて、洗面所で顔を洗います。", furigana: "あさおきて、せんめんじょでかおをあらいます。", en: "早上起床在盥洗室洗臉。" }] },
  { id: "v_h_gareeji", word: "ガレージ", furigana: "がれーじ", romaji: "gareeji", meaning: "車庫", level: "N4", category: "housing_space",
    sentences: [{ ja: "車をガレージに入れます。", furigana: "くるまをがれーじにいれます。", en: "把車子停進車庫。" }] },
  { id: "v_h_kaaten", word: "カーテン", furigana: "かーてん", romaji: "kaaten", meaning: "窗簾", level: "N5", category: "housing_space",
    sentences: [{ ja: "朝起きてカーテンを開けます。", furigana: "あさおきてかーてんをあけます。", en: "早上起床拉開窗簾。" }] },
  { id: "v_h_juutan", word: "絨毯", furigana: "じゅうたん", romaji: "juutan", meaning: "地毯", level: "N4", category: "housing_space",
    sentences: [{ ja: "部屋にふかふかの絨毯を敷きました。", furigana: "へやにふかふかのじゅうたんをしきました。", en: "在房間鋪了軟綿綿的地毯。" }] },
  { id: "v_h_zabuton", word: "座布団", furigana: "ざぶとん", romaji: "zabuton", meaning: "坐墊", level: "N4", category: "housing_space",
    sentences: [{ ja: "畳の上に座布団を置きます。", furigana: "たたみのうえにざぶとんをおきます。", en: "在榻榻米上放坐墊。" }] },
  { id: "v_h_hikidashi", word: "引き出し", furigana: "ひきだし", romaji: "hikidashi", meaning: "抽屜", level: "N4", category: "housing_space",
    sentences: [{ ja: "ハサミは机の引き出しにあります。", furigana: "はさみはつくえのひきだしにあります。", en: "剪刀在書桌的抽屜裡。" }] },
  { id: "v_h_oshiire", word: "押し入れ", furigana: "おしいれ", romaji: "oshiire", meaning: "壁櫥", level: "N4", category: "housing_space",
    sentences: [{ ja: "布団を押し入れに片付けます。", furigana: "ふとんをおしいれにかたづけます。", en: "把棉被收進壁櫥裡。" }] },
  { id: "v_h_kagi", word: "鍵", furigana: "かぎ", romaji: "kagi", meaning: "鑰匙", level: "N5", category: "housing_space",
    sentences: [{ ja: "出かける時は必ず鍵をかけます。", furigana: "でかけるときはかならずかぎをかけます。", en: "出門時一定會鎖門。" }] },
  { id: "v_h_senpuuki", word: "扇風機", furigana: "せんぷうき", romaji: "senpuuki", meaning: "電風扇", level: "N4", category: "housing_space",
    sentences: [{ ja: "暑いので扇風機をつけます。", furigana: "あついのでせんぷうきをつけます。", en: "因為很熱所以開電風扇。" }] },
  { id: "v_h_airon", word: "アイロン", furigana: "あいろん", romaji: "airon", meaning: "熨斗", level: "N4", category: "housing_space",
    sentences: [{ ja: "シャツにアイロンをかけます。", furigana: "しゃつにあいろんをかけます。", en: "用熨斗燙襯衫。" }] },
  { id: "v_h_suihanki", word: "炊飯器", furigana: "すいはんき", romaji: "suihanki", meaning: "電鍋 / 電子鍋", level: "N4", category: "housing_space",
    sentences: [{ ja: "炊飯器でご飯を炊きます。", furigana: "すいはんきでごはんをたきます。", en: "用電子鍋煮飯。" }] },
  { id: "v_h_fuku_clean", word: "拭く", furigana: "ふく", romaji: "fuku", meaning: "擦拭", level: "N4", category: "housing_space",
    sentences: [{ ja: "雑巾でテーブルを拭きます。", furigana: "ぞうきんでてーぶるをふきます。", en: "用抹布擦桌子。" }] },
  { id: "v_h_haku_sweep", word: "掃く", furigana: "はく", romaji: "haku", meaning: "掃", level: "N4", category: "housing_space",
    sentences: [{ ja: "ほうきで庭を掃きます。", furigana: "ほうきでにわをはきます。", en: "用掃把掃庭院。" }] },
  { id: "v_h_hosu", word: "干す", furigana: "ほす", romaji: "hosu", meaning: "晾 / 曬", level: "N3", category: "housing_space",
    sentences: [{ ja: "ベランダに洗濯物を干します。", furigana: "べらんだにせんたくものをほします。", en: "在陽台晾衣服。" }] },
  { id: "v_h_tatamu", word: "畳む", furigana: "たたむ", romaji: "tatamu", meaning: "摺疊", level: "N3", category: "housing_space",
    sentences: [{ ja: "乾いた服をきれいに畳みます。", furigana: "かわいたふくをきれいにたたみます。", en: "把乾了的衣服摺整齊。" }] },

  // ================= 交通與移動 (transport_mobility) Part 2 =================
  { id: "v_t_tonneru", word: "トンネル", furigana: "とんねる", romaji: "tonneru", meaning: "隧道", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "車でトンネルを抜けます。", furigana: "くるまでとんねるをぬけます。", en: "開車穿過隧道。" }] },
  { id: "v_t_hashi", word: "橋", furigana: "はし", romaji: "hashi", meaning: "橋", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "川に大きな橋がかかっています。", furigana: "かわにおおきなはしがかかっています。", en: "河上架著一座大橋。" }] },
  { id: "v_t_kousokudouro", word: "高速道路", furigana: "こうそくどうろ", romaji: "kousokudouro", meaning: "高速公路", level: "N3", category: "transport_mobility",
    sentences: [{ ja: "高速道路を走って海へ行きます。", furigana: "こうそくどうろをはしってうみへいきます。", en: "開高速公路去海邊。" }] },
  { id: "v_t_kaisatsu", word: "改札", furigana: "かいさつ", romaji: "kaisatsu", meaning: "剪票口 / 驗票閘門", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "改札口で友達と待ち合わせます。", furigana: "かいさつぐちでともだちとまちあわせます。", en: "在剪票口和朋友碰面。" }] },
  { id: "v_t_hoomu", word: "ホーム", furigana: "ほーむ", romaji: "hoomu", meaning: "月台", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "駅のホームで電車を待ちます。", furigana: "えきのほーむででんしゃをまちます。", en: "在車站月台等電車。" }] },
  { id: "v_t_senro", word: "線路", furigana: "せんろ", romaji: "senro", meaning: "鐵軌", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "線路の近くに住んでいます。", furigana: "せんろのちかくにすんでいます。", en: "住在鐵軌附近。" }] },
  { id: "v_t_tokkyuu", word: "特急", furigana: "とっきゅう", romaji: "tokkyuu", meaning: "特快車", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "急ぐ時は特急電車に乗ります。", furigana: "いすぐときはとっきゅうでんしゃにのります。", en: "趕時間時會搭特快車。" }] },
  { id: "v_t_shuuten", word: "終点", furigana: "しゅうてん", romaji: "shuuten", meaning: "終點站", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "この電車は次が終点です。", furigana: "このでんしゃはつぎがしゅうてんです。", en: "這班電車下一站就是終點站了。" }] },
  { id: "v_t_manindensha", word: "満員電車", furigana: "まんいんでんしゃ", romaji: "manindensha", meaning: "客滿的電車", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "毎朝、満員電車に乗って通勤します。", furigana: "まいあさ、まんいんでんしゃにのってつうきんします。", en: "每天早上擠滿員電車通勤。" }] },
  { id: "v_t_jiko", word: "事故", furigana: "じこ", romaji: "jiko", meaning: "車禍 / 事故", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "高速道路で大きな事故がありました。", furigana: "こうそくどうろでおおきなじこがありました。", en: "高速公路上發生了重大車禍。" }] },
  { id: "v_t_juutai", word: "渋滞", furigana: "じゅうたい", romaji: "juutai", meaning: "塞車", level: "N3", category: "transport_mobility",
    sentences: [{ ja: "道が渋滞していて、会社に遅れました。", furigana: "みちがじゅうたいしていて、かいしゃにおくれました。", en: "因為塞車，去公司遲到了。" }] },
  { id: "v_t_wataru", word: "渡る", furigana: "わたる", romaji: "wataru", meaning: "過(馬路/橋)", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "横断歩道を渡ります。", furigana: "おうだんほどうをわたります。", en: "過行人穿越道。" }] },
  { id: "v_t_magaru", word: "曲がる", furigana: "まがる", romaji: "magaru", meaning: "轉彎", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "次の交差点を右に曲がってください。", furigana: "つぎのこうさてんをみぎにまがってください。", en: "請在下一個十字路口右轉。" }] },
  { id: "v_t_susumu", word: "進む", furigana: "すすむ", romaji: "susumu", meaning: "前進", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "車をゆっくり前に進めます。", furigana: "くるまをゆっくりまえにすすめます。", en: "把車慢慢往前開。" }] },
  { id: "v_t_modoru", word: "戻る", furigana: "もどる", romaji: "modoru", meaning: "返回 / 回到", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "忘れ物をしたので家に戻ります。", furigana: "わすれものをしたのでいえにもどります。", en: "因為忘記帶東西所以回家拿。" }] },
  { id: "v_t_mayou", word: "迷う", furigana: "まよう", romaji: "mayou", meaning: "迷路 / 猶豫", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "道に迷ってしまいました。", furigana: "みちにまよってしまいました。", en: "不小心迷路了。" }] },
  { id: "v_t_ma_ni_au", word: "間に合う", furigana: "まにあう", romaji: "maniau", meaning: "趕上 / 來得及", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "走れば電車に間に合います。", furigana: "はしればでんしゃにまにあいます。", en: "用跑的話就趕得上電車。" }] },
  { id: "v_t_okureru", word: "遅れる", furigana: "おくれる", romaji: "okureru", meaning: "遲到 / 誤點", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "雪で電車が遅れています。", furigana: "ゆきででんしゃがおくれています。", en: "因為下雪，電車誤點了。" }] },

  // ================= 休閒育樂與購物 (leisure_sports) Part 2 =================
  { id: "v_l_rejibukuro", word: "レジ袋", furigana: "れじぶくろ", romaji: "rejibukuro", meaning: "塑膠袋", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "レジ袋は有料です。", furigana: "れじぶくろはゆうりょうです。", en: "塑膠袋是要收費的。" }] },
  { id: "v_l_seeru", word: "セール", furigana: "せーる", romaji: "seeru", meaning: "特賣", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "今、デパートでセールをやっています。", furigana: "いま、でぱーとでせーるをやっています。", en: "現在百貨公司正在舉辦特賣。" }] },
  { id: "v_l_hangaku", word: "半額", furigana: "はんがく", romaji: "hangaku", meaning: "半價", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "このお弁当は半額になっています。", furigana: "このおべんとうははんがくになっています。", en: "這個便當現在半價。" }] },
  { id: "v_l_waribiki", word: "割引", furigana: "わりびき", romaji: "waribiki", meaning: "折扣", level: "N3", category: "leisure_sports",
    sentences: [{ ja: "学生証を見せると割引になります。", furigana: "がくせいしょうをみせるとわりびきになります。", en: "出示學生證會有折扣。" }] },
  { id: "v_l_reshiito", word: "レシート", furigana: "れしーと", romaji: "reshiito", meaning: "收據 (發票)", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "レシートは要りません。", furigana: "れしーとはいりません。", en: "我不需要收據。" }] },
  { id: "v_l_ryoushuusho", word: "領収書", furigana: "りょうしゅうしょ", romaji: "ryoushuusho", meaning: "收據", level: "N3", category: "leisure_sports",
    sentences: [{ ja: "領収書をください。", furigana: "りょうしゅうしょをください。", en: "請給我收據。" }] },
  { id: "v_l_kamera", word: "カメラ", furigana: "かめら", romaji: "kamera", meaning: "相機", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "新しいカメラで写真を撮ります。", furigana: "あたらしいかめらでしゃしんをとります。", en: "用新相機拍照。" }] },
  { id: "v_l_gitaa", word: "ギター", furigana: "ぎたー", romaji: "gitaa", meaning: "吉他", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "毎日ギターの練習をします。", furigana: "まいにちぎたーのれんしゅうをします。", en: "每天練習吉他。" }] },
  { id: "v_l_piano", word: "ピアノ", furigana: "ぴあの", romaji: "piano", meaning: "鋼琴", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "子供の頃からピアノを弾いています。", furigana: "こどものころからぴあのをひいています。", en: "從小就在彈鋼琴。" }] },
  { id: "v_l_karaoke", word: "カラオケ", furigana: "からおけ", romaji: "karaoke", meaning: "卡拉OK", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "友達とカラオケに行って歌います。", furigana: "ともだちとからおけにいってうたいます。", en: "和朋友去卡拉OK唱歌。" }] },
  { id: "v_l_tsuri", word: "釣り", furigana: "つり", romaji: "tsuri", meaning: "釣魚", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "休みの日は海へ釣りに行きます。", furigana: "やすみのひはうみへつりにいきます。", en: "放假時去海邊釣魚。" }] },
  { id: "v_l_tozan", word: "登山", furigana: "とざん", romaji: "tozan", meaning: "登山", level: "N3", category: "leisure_sports",
    sentences: [{ ja: "秋の登山は景色がきれいです。", furigana: "あきのとざんはけしきがきれいです。", en: "秋天登山風景很美。" }] },
  { id: "v_l_konsaato", word: "コンサート", furigana: "こんさーと", romaji: "konsaato", meaning: "演唱會 / 音樂會", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "大好きな歌手のコンサートに行きます。", furigana: "だいすきなかしゅのこんさーとにいきます。", en: "去聽最喜歡的歌手的演唱會。" }] },
  { id: "v_l_tenrankai", word: "展覧会", furigana: "てんらんかい", romaji: "tenrankai", meaning: "展覽會", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "美術館の展覧会を見に行きます。", furigana: "びじゅつかんのてんらんかいをみにいきます。", en: "去看美術館的展覽會。" }] },
  { id: "v_l_paatii", word: "パーティー", furigana: "ぱーてぃー", romaji: "paatii", meaning: "派對", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "週末に誕生日パーティーをします。", furigana: "しゅうまつにたんじょうびぱーてぃーをします。", en: "週末要辦生日派對。" }] },
  { id: "v_l_gorufu", word: "ゴルフ", furigana: "ごるふ", romaji: "gorufu", meaning: "高爾夫", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "日曜日は社長とゴルフに行きます。", furigana: "にちようびはしゃちょうとごるふにいきます。", en: "星期天要和社長去打高爾夫。" }] },
  { id: "v_l_ryokan", word: "旅館", furigana: "りょかん", romaji: "ryokan", meaning: "日式旅館", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "日本の古い旅館に泊まりたいです。", furigana: "にほんのふるいりょかにとまりたいです。", en: "想住在日本古老的旅館裡。" }] },
  { id: "v_l_yoyaku", word: "予約", furigana: "よやく", romaji: "yoyaku", meaning: "預約 / 訂房", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "インターネットでホテルを予約します。", furigana: "いんたーねっとでほてるをよやくします。", en: "在網路上預訂飯店。" }] },
  { id: "v_l_chekkuin", word: "チェックイン", furigana: "ちぇっくいん", romaji: "chekkuin", meaning: "報到 / 入住", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "３時になったらホテルにチェックインできます。", furigana: "さんじになったらほてるにちぇっくいんできます。", en: "到了三點就可以登記入住飯店。" }] },
  { id: "v_l_azukeru", word: "預ける", furigana: "あずける", romaji: "azukeru", meaning: "寄放", level: "N3", category: "leisure_sports",
    sentences: [{ ja: "駅のロッカーに荷物を預けます。", furigana: "えきのろっかーににもつをあずけます。", en: "把行李寄放在車站的置物櫃裡。" }] }
];

const n5Content = fs.readFileSync(n5File, 'utf8');
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(n5Content, sandbox);
const db = sandbox.window.JLPT_DATA_CHUNKS["N5"];

// Avoid duplicates
const existingWords = new Set(db.vocabulary.map(v => v.word));
const newWords = megaWordsPt2.filter(v => !existingWords.has(v.word));

db.vocabulary = db.vocabulary.concat(newWords);

const outputCode = "window.JLPT_DATA_CHUNKS = window.JLPT_DATA_CHUNKS || {};\n" +
"window.JLPT_DATA_CHUNKS[\"N5\"] = " + JSON.stringify(db, null, 2) + ";\n" +
"if (typeof module !== 'undefined') { module.exports = window.JLPT_DATA_CHUNKS[\"N5\"]; }\n";

fs.writeFileSync(n5File, outputCode, 'utf8');
console.log('Appended', newWords.length, 'Mega material life words (Part 2) to data_n5.js!');
