const fs = require('fs');
const path = require('path');
const vm = require('vm');

const srcDir = 'C:\\Users\\O1004\\.gemini\\antigravity\\scratch\\jlpt-n5-textbook';
const n5File = path.join(srcDir, 'data_n5.js');

const megaWords = [
  // ================= 飲食文化 (food_culture) =================
  { id: "v_f_suppai", word: "酸っぱい", furigana: "すっぱい", romaji: "suppai", meaning: "酸的", level: "N4", category: "food_culture",
    sentences: [{ ja: "レモンはとても酸っぱいです。", furigana: "れもんはとてもすっぱいです。", en: "檸檬非常酸。" }] },
  { id: "v_f_shoppai", word: "しょっぱい", furigana: "しょっぱい", romaji: "shoppai", meaning: "鹹的", level: "N4", category: "food_culture",
    sentences: [{ ja: "塩を入れすぎて、スープがしょっぱいです。", furigana: "しおをいれすぎて、すーぷがしょっぱいです。", en: "鹽加太多，湯很鹹。" }] },
  { id: "v_f_nigai", word: "苦い", furigana: "にがい", romaji: "nigai", meaning: "苦的", level: "N4", category: "food_culture",
    sentences: [{ ja: "この薬は苦くて飲めません。", furigana: "このくすりはにがくてのめません。", en: "這個藥很苦吞不下去。" }] },
  { id: "v_f_koi", word: "濃い", furigana: "こい", romaji: "koi", meaning: "濃的 / 重口味的", level: "N3", category: "food_culture",
    sentences: [{ ja: "味が濃い料理が好きです。", furigana: "あじがこいりょうりがすきです。", en: "喜歡口味重的料理。" }] },
  { id: "v_f_usui", word: "薄い", furigana: "うすい", romaji: "usui", meaning: "淡的", level: "N3", category: "food_culture",
    sentences: [{ ja: "味が薄かったら、醤油をかけてください。", furigana: "あじがうすかったら、しょうゆをかけてください。", en: "如果味道淡，請加點醬油。" }] },
  { id: "v_f_nioi", word: "匂い", furigana: "におい", romaji: "nioi", meaning: "氣味 / 香味", level: "N4", category: "food_culture",
    sentences: [{ ja: "台所からいい匂いがします。", furigana: "だいどころからいいにおいがします。", en: "廚房傳來好聞的香味。" }] },
  { id: "v_f_niru", word: "煮る", furigana: "にる", romaji: "niru", meaning: "煮 / 燉", level: "N4", category: "food_culture",
    sentences: [{ ja: "野菜と肉を鍋で煮ます。", furigana: "やさいとにくをなべでにます。", en: "在鍋裡燉蔬菜和肉。" }] },
  { id: "v_f_yaku", word: "焼く", furigana: "やく", romaji: "yaku", meaning: "烤 / 煎", level: "N4", category: "food_culture",
    sentences: [{ ja: "魚をきれいに焼きました。", furigana: "さかなをきれいにやきました。", en: "把魚烤得很漂亮。" }] },
  { id: "v_f_ageru", word: "揚げる", furigana: "あげる", romaji: "ageru", meaning: "油炸", level: "N4", category: "food_culture",
    sentences: [{ ja: "油でポテトを揚げます。", furigana: "あぶらでぽてとをあげます。", en: "用油炸薯條。" }] },
  { id: "v_f_yuderu", word: "茹でる", furigana: "ゆでる", romaji: "yuderu", meaning: "用水煮 / 汆燙", level: "N4", category: "food_culture",
    sentences: [{ ja: "お湯で卵を茹でます。", furigana: "おゆでたまごをゆでます。", en: "用熱水煮蛋。" }] },
  { id: "v_f_mazeru", word: "混ぜる", furigana: "まぜる", romaji: "mazeru", meaning: "攪拌", level: "N3", category: "food_culture",
    sentences: [{ ja: "卵と砂糖をよく混ぜます。", furigana: "たまごとさとうをよくまぜます。", en: "將蛋和糖充分攪拌。" }] },
  { id: "v_f_atatameru", word: "温める", furigana: "あたためる", romaji: "atatameru", meaning: "加熱", level: "N4", category: "food_culture",
    sentences: [{ ja: "お弁当を電子レンジで温めます。", furigana: "おべんとうをでんしれんじであたためます。", en: "用微波爐加熱便當。" }] },
  { id: "v_f_wakasu", word: "沸かす", furigana: "わかす", romaji: "wakasu", meaning: "燒開(水)", level: "N4", category: "food_culture",
    sentences: [{ ja: "お茶を飲むためにお湯を沸かします。", furigana: "おちゃをのむためにおゆをわかします。", en: "為了喝茶而燒開水。" }] },
  { id: "v_f_kizamu", word: "刻む", furigana: "きざむ", romaji: "kizamu", meaning: "切碎", level: "N3", category: "food_culture",
    sentences: [{ ja: "ネギを細かく刻みます。", furigana: "ねぎをこまかくきざみます。", en: "把蔥切得很細。" }] },
  { id: "v_f_muku", word: "剥く", furigana: "むく", romaji: "muku", meaning: "剝皮", level: "N3", category: "food_culture",
    sentences: [{ ja: "りんごの皮を剥きます。", furigana: "りんごのかわをむきます。", en: "削蘋果皮。" }] },
  { id: "v_f_hashi", word: "箸", furigana: "はし", romaji: "hashi", meaning: "筷子", level: "N5", category: "food_culture",
    sentences: [{ ja: "日本人は箸を使ってご飯を食べます。", furigana: "にほんじんははしをつかってごはんをたべます。", en: "日本人用筷子吃飯。" }] },
  { id: "v_f_supuun", word: "スプーン", furigana: "すぷーん", romaji: "supuun", meaning: "湯匙", level: "N5", category: "food_culture",
    sentences: [{ ja: "スプーンでスープを飲みます。", furigana: "すぷーんですーぷをのみます。", en: "用湯匙喝湯。" }] },
  { id: "v_f_fooku", word: "フォーク", furigana: "ふぉーく", romaji: "fooku", meaning: "叉子", level: "N5", category: "food_culture",
    sentences: [{ ja: "フォークとナイフでステーキを切ります。", furigana: "ふぉーくとないふですてーきをきります。", en: "用叉子和刀子切牛排。" }] },
  { id: "v_f_osara", word: "お皿", furigana: "おさら", romaji: "osara", meaning: "盤子", level: "N5", category: "food_culture",
    sentences: [{ ja: "きれいなお皿に料理をのせます。", furigana: "きれいなおさらにりょうりをのせます。", en: "把料理裝在漂亮的盤子上。" }] },
  { id: "v_f_chawan", word: "茶碗", furigana: "ちゃわん", romaji: "chawan", meaning: "飯碗", level: "N4", category: "food_culture",
    sentences: [{ ja: "ご飯を茶碗によそいます。", furigana: "ごはんをちゃわんによそいます。", en: "把飯盛到碗裡。" }] },
  { id: "v_f_koppu", word: "コップ", furigana: "こっぷ", romaji: "koppu", meaning: "杯子 (無把手的水杯)", level: "N5", category: "food_culture",
    sentences: [{ ja: "コップに水を注ぎます。", furigana: "こっぷにみずをそそぎます。", en: "把水倒進杯子裡。" }] },
  { id: "v_f_nabe", word: "鍋", furigana: "なべ", romaji: "nabe", meaning: "鍋子", level: "N4", category: "food_culture",
    sentences: [{ ja: "大きな鍋でスープを作ります。", furigana: "おおきななべですーぷをつくります。", en: "用大鍋子煮湯。" }] },
  { id: "v_f_furaipan", word: "フライパン", furigana: "ふらいぱん", romaji: "furaipan", meaning: "平底鍋", level: "N4", category: "food_culture",
    sentences: [{ ja: "フライパンで卵を焼きます。", furigana: "ふらいぱんでたまごをやきます。", en: "用平底鍋煎蛋。" }] },
  { id: "v_f_houchou", word: "包丁", furigana: "ほうちょう", romaji: "houchou", meaning: "菜刀", level: "N3", category: "food_culture",
    sentences: [{ ja: "よく切れる包丁で肉を切ります。", furigana: "よくきれるほうちょうでにくをきります。", en: "用很利的菜刀切肉。" }] },
  { id: "v_f_manaita", word: "まな板", furigana: "まないた", romaji: "manaita", meaning: "砧板", level: "N3", category: "food_culture",
    sentences: [{ ja: "まな板の上で野菜を切ります。", furigana: "まないたのうえでやさいをきります。", en: "在砧板上切菜。" }] },
  { id: "v_f_menyuu", word: "メニュー", furigana: "めにゅー", romaji: "menyuu", meaning: "菜單", level: "N5", category: "food_culture",
    sentences: [{ ja: "すみません、メニューを見せてください。", furigana: "すみません、めにゅーをみせてください。", en: "不好意思，請給我看一下菜單。" }] },
  { id: "v_f_chuumon", word: "注文", furigana: "ちゅうもん", romaji: "chuumon", meaning: "點餐", level: "N4", category: "food_culture",
    sentences: [{ ja: "ハンバーグを一つ注文しました。", furigana: "はんばーぐをひとつちゅうもんしました。", en: "點了一個漢堡排。" }] },
  { id: "v_f_okaikei", word: "お会計", furigana: "おかいけい", romaji: "okaikei", meaning: "結帳", level: "N5", category: "food_culture",
    sentences: [{ ja: "お会計をお願いします。", furigana: "おかいけいをおねがいします。", en: "麻煩結帳。" }] },
  { id: "v_f_gochisousama", word: "ごちそうさまでした", furigana: "ごちそうさまでした", romaji: "gochisousamadeshita", meaning: "多謝款待", level: "N5", category: "food_culture",
    sentences: [{ ja: "食べ終わったら、「ごちそうさまでした」と言います。", furigana: "たべおわったら、「ごちそうさまでした」といいます。", en: "吃完後，要說「多謝款待」。" }] },
  { id: "v_f_itadakimasu", word: "いただきます", furigana: "いただきます", romaji: "itadakimasu", meaning: "我開動了", level: "N5", category: "food_culture",
    sentences: [{ ja: "食べる前に「いただきます」と言います。", furigana: "たべるまえに「いただきます」といいます。", en: "吃之前要說「我開動了」。" }] },
  { id: "v_f_shokudou", word: "食堂", furigana: "しょくどう", romaji: "shokudou", meaning: "餐廳 / 食堂", level: "N5", category: "food_culture",
    sentences: [{ ja: "会社の食堂で昼ご飯を食べます。", furigana: "かいしゃのしょくどうでひるごはんをたべます。", en: "在公司的員工餐廳吃午餐。" }] },
  { id: "v_f_karee", word: "カレー", furigana: "かれー", romaji: "karee", meaning: "咖哩", level: "N5", category: "food_culture",
    sentences: [{ ja: "日本のカレーライスは美味しいです。", furigana: "にほんのかれーらいすはおいしいです。", en: "日本的咖哩飯很好吃。" }] },
  { id: "v_f_raamen", word: "ラーメン", furigana: "らーめん", romaji: "raamen", meaning: "拉麵", level: "N5", category: "food_culture",
    sentences: [{ ja: "寒い日は熱いラーメンが食べたくなります。", furigana: "さむいひはあついらーめんがたべたくなります。", en: "冷天就想吃熱呼呼的拉麵。" }] },
  { id: "v_f_udon", word: "うどん", furigana: "うどん", romaji: "udon", meaning: "烏龍麵", level: "N5", category: "food_culture",
    sentences: [{ ja: "昼ご飯はうどんにします。", furigana: "ひるごはんはうどんにします。", en: "午餐吃烏龍麵。" }] },
  { id: "v_f_soba", word: "そば", furigana: "そば", romaji: "soba", meaning: "蕎麥麵", level: "N5", category: "food_culture",
    sentences: [{ ja: "冷たいおそばが好きです。", furigana: "つめたいおそばがすきです。", en: "喜歡冷蕎麥麵。" }] },
  { id: "v_f_sushi", word: "寿司", furigana: "すし", romaji: "sushi", meaning: "壽司", level: "N5", category: "food_culture",
    sentences: [{ ja: "北海道でお寿司を食べました。", furigana: "ほっかいどうでおすしをたべました。", en: "在北海道吃了壽司。" }] },
  { id: "v_f_sashimi", word: "刺身", furigana: "さしみ", romaji: "sashimi", meaning: "生魚片", level: "N4", category: "food_culture",
    sentences: [{ ja: "マグロの刺身が一番好きです。", furigana: "まぐろのさしみがいちばんすきです。", en: "最喜歡鮪魚生魚片。" }] },
  { id: "v_f_suteeki", word: "ステーキ", furigana: "すてーき", romaji: "suteeki", meaning: "牛排", level: "N4", category: "food_culture",
    sentences: [{ ja: "誕生日なので、ステーキを食べに行きます。", furigana: "たんじょうびなので、すてーきをたべにいきます。", en: "因為是生日，所以去吃牛排。" }] },
  { id: "v_f_sarada", word: "サラダ", furigana: "さらだ", romaji: "sarada", meaning: "沙拉", level: "N5", category: "food_culture",
    sentences: [{ ja: "野菜サラダを作りました。", furigana: "やさいさらだをつくりました。", en: "做了蔬菜沙拉。" }] },
  { id: "v_f_suupu", word: "スープ", furigana: "すーぷ", romaji: "suupu", meaning: "湯", level: "N5", category: "food_culture",
    sentences: [{ ja: "温かいコーンスープを飲みます。", furigana: "あたたかいこーんすーぷをのみます。", en: "喝熱的玉米濃湯。" }] },
  { id: "v_f_misoshiru", word: "味噌汁", furigana: "みそしる", romaji: "misoshiru", meaning: "味噌湯", level: "N4", category: "food_culture",
    sentences: [{ ja: "毎朝、ご飯と味噌汁を食べます。", furigana: "まいあさ、ごはんとみそしるをたべます。", en: "每天早上吃飯配味噌湯。" }] },
  { id: "v_f_onigiri", word: "おにぎり", furigana: "おにぎり", romaji: "onigiri", meaning: "飯糰", level: "N5", category: "food_culture",
    sentences: [{ ja: "コンビニで鮭のおにぎりを買いました。", furigana: "こんびにでさけのおにぎりをかいました。", en: "在便利商店買了鮭魚飯糰。" }] },
  { id: "v_f_tenpura", word: "天ぷら", furigana: "てんぷら", romaji: "tenpura", meaning: "天婦羅", level: "N5", category: "food_culture",
    sentences: [{ ja: "エビの天ぷらが美味しいです。", furigana: "えびのてんぷらがおいしいです。", en: "炸蝦天婦羅很好吃。" }] },
  { id: "v_f_okashi", word: "お菓子", furigana: "おかし", romaji: "okashi", meaning: "零食", level: "N5", category: "food_culture",
    sentences: [{ ja: "子供たちにお菓子をあげます。", furigana: "こどもたちにおかしをあげます。", en: "給孩子們零食。" }] },
  { id: "v_f_keeki", word: "ケーキ", furigana: "けーき", romaji: "keeki", meaning: "蛋糕", level: "N5", category: "food_culture",
    sentences: [{ ja: "誕生日にケーキを買いました。", furigana: "たんじょうびにけーきをかいました。", en: "生日買了蛋糕。" }] },
  { id: "v_f_aisukuriimu", word: "アイスクリーム", furigana: "あいすくりーむ", romaji: "aisukuriimu", meaning: "冰淇淋", level: "N5", category: "food_culture",
    sentences: [{ ja: "暑いのでアイスクリームが食べたいです。", furigana: "あついのであいすくりーむがたべたいです。", en: "因為很熱所以想吃冰淇淋。" }] },
  { id: "v_f_chokoreeto", word: "チョコレート", furigana: "ちょこれーと", romaji: "chokoreeto", meaning: "巧克力", level: "N5", category: "food_culture",
    sentences: [{ ja: "バレンタインにチョコレートをもらいました。", furigana: "ばれんたいんにちょこれーとをもらいました。", en: "情人節收到了巧克力。" }] },
  { id: "v_f_biiru", word: "ビール", furigana: "びーる", romaji: "biiru", meaning: "啤酒", level: "N5", category: "food_culture",
    sentences: [{ ja: "仕事の後のビールは最高です。", furigana: "しごとのあとのびーるはさいこうです。", en: "下班後的啤酒是最棒的。" }] },
  { id: "v_f_juusu", word: "ジュース", furigana: "じゅーす", romaji: "juusu", meaning: "果汁 / 飲料", level: "N5", category: "food_culture",
    sentences: [{ ja: "オレンジジュースを一杯ください。", furigana: "おれんじじゅーすをいっぱいください。", en: "請給我一杯柳橙汁。" }] },

  // ================= 服飾與美容 (fashion_beauty) =================
  { id: "v_c_fuku", word: "服", furigana: "ふく", romaji: "fuku", meaning: "衣服", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "デパートで新しい服を買いました。", furigana: "でぱーとであたらしいふくをかいました。", en: "在百貨公司買了新衣服。" }] },
  { id: "v_c_shatsu", word: "シャツ", furigana: "しゃつ", romaji: "shatsu", meaning: "襯衫", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "白いシャツを着ています。", furigana: "しろいしゃつをきています。", en: "穿著白襯衫。" }] },
  { id: "v_c_seetaa", word: "セーター", furigana: "せーたー", romaji: "seetaa", meaning: "毛衣", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "冬は暖かいセーターが必要です。", furigana: "ふゆはあたたかいせーたーがひつようです。", en: "冬天需要溫暖的毛衣。" }] },
  { id: "v_c_kooto", word: "コート", furigana: "こーと", romaji: "kooto", meaning: "大衣 / 外套", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "寒いのでコートを着て出かけます。", furigana: "さむいのでこーとをきてでかけます。", en: "因為很冷，所以穿上大衣出門。" }] },
  { id: "v_c_suutsu", word: "スーツ", furigana: "すーつ", romaji: "suutsu", meaning: "西裝", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "会社にはスーツで行きます。", furigana: "かいしゃにはすーつでいきます。", en: "穿西裝去公司。" }] },
  { id: "v_c_zubon", word: "ズボン", furigana: "ずぼん", romaji: "zubon", meaning: "褲子", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "黒いズボンを履いています。", furigana: "くろいずぼんをはいています。", en: "穿著黑褲子。" }] },
  { id: "v_c_sukaato", word: "スカート", furigana: "すかーと", romaji: "sukaato", meaning: "裙子", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "彼女は短いスカートを履いています。", furigana: "かのじょはみじかいすかーとをはいています。", en: "她穿著短裙。" }] },
  { id: "v_c_shitagi", word: "下着", furigana: "したぎ", romaji: "shitagi", meaning: "內衣", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "毎日きれいな下着に着替えます。", furigana: "まいにちきれいなしたぎにきがえます。", en: "每天換乾淨的內衣。" }] },
  { id: "v_c_kutsushita", word: "靴下", furigana: "くつした", romaji: "kutsushita", meaning: "襪子", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "靴下を脱いで部屋に入ります。", furigana: "くつしたをぬいでへやにはいります。", en: "脫掉襪子進房間。" }] },
  { id: "v_c_boushi", word: "帽子", furigana: "ぼうし", romaji: "boushi", meaning: "帽子", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "日差しが強いので帽子を被ります。", furigana: "ひざしがつよいのでぼうしをかぶります。", en: "陽光很強所以戴帽子。" }] },
  { id: "v_c_nekutai", word: "ネクタイ", furigana: "ねくたい", romaji: "nekutai", meaning: "領帶", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "スーツに赤いネクタイをします。", furigana: "すーつにあかいねくたいをします。", en: "西裝搭配紅領帶。" }] },
  { id: "v_c_tebukuro", word: "手袋", furigana: "てぶくろ", romaji: "tebukuro", meaning: "手套", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "雪が降っているので手袋をします。", furigana: "ゆきがふっているのでてぶくろをします。", en: "正在下雪，所以戴上手套。" }] },
  { id: "v_c_kutsu", word: "靴", furigana: "くつ", romaji: "kutsu", meaning: "鞋子", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "新しい靴を買いました。", furigana: "あたらしいくつをかいました。", en: "買了新鞋子。" }] },
  { id: "v_c_sunikaa", word: "スニーカー", furigana: "すにかー", romaji: "sunikaa", meaning: "運動鞋", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "歩きやすいスニーカーで旅行に行きます。", furigana: "あるきやすいすにかーでりょこうにいきます。", en: "穿著好走的運動鞋去旅行。" }] },
  { id: "v_c_kaban", word: "かばん", furigana: "かばん", romaji: "kaban", meaning: "包包", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "このかばんはとても重いです。", furigana: "このかばんはとてもおもいです。", en: "這個包包很重。" }] },
  { id: "v_c_saifu", word: "財布", furigana: "さいふ", romaji: "saifu", meaning: "錢包", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "財布を落としてしまいました。", furigana: "さいふをおとしてしまいました。", en: "不小心把錢包弄丟了。" }] },
  { id: "v_c_tokei", word: "時計", furigana: "とけい", romaji: "tokei", meaning: "手錶 / 時鐘", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "時計を見て時間を確認します。", furigana: "とけいをみてじかんをかくにんします。", en: "看手錶確認時間。" }] },
  { id: "v_c_megane", word: "眼鏡", furigana: "めがね", romaji: "megane", meaning: "眼鏡", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "本を読む時は眼鏡をかけます。", furigana: "ほんをよむときはめがねをかけます。", en: "看書時會戴眼鏡。" }] },
  { id: "v_c_yubiwa", word: "指輪", furigana: "ゆびわ", romaji: "yubiwa", meaning: "戒指", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "結婚指輪を左手にはめます。", furigana: "けっこんゆびわをひだりてにはめます。", en: "把結婚戒指戴在左手。" }] },
  { id: "v_c_keshou", word: "化粧", furigana: "けしょう", romaji: "keshou", meaning: "化妝", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "毎朝、化粧をするのに時間がかかります。", furigana: "まいあさ、けしょうをするのにじかんがかかります。", en: "每天早上化妝要花很多時間。" }] },
  { id: "v_c_kagami", word: "鏡", furigana: "かがみ", romaji: "kagami", meaning: "鏡子", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "鏡を見て髪を直します。", furigana: "かがみをみてかみをなおします。", en: "照著鏡子整理頭髮。" }] },
  { id: "v_c_biyouin", word: "美容院", furigana: "びよういん", romaji: "biyouin", meaning: "美容院", level: "N4", category: "fashion_beauty",
    sentences: [{ ja: "美容院で髪を切ってもらいました。", furigana: "びよういんでかみをきってもらいました。", en: "在美容院剪了頭髮。" }] },
  { id: "v_c_kiru_wear", word: "着る", furigana: "きる", romaji: "kiru", meaning: "穿 (上衣)", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "寒いのでジャケットを着ます。", furigana: "さむいのでじゃけっとをきます。", en: "因為很冷所以穿夾克。" }] },
  { id: "v_c_haku_wear", word: "履く", furigana: "はく", romaji: "haku", meaning: "穿 (鞋子/褲子)", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "靴を履いて外に出ます。", furigana: "くつをはいてそとにでます。", en: "穿上鞋子出門。" }] },
  { id: "v_c_kaburu", word: "被る", furigana: "かぶる", romaji: "kaburu", meaning: "戴 (帽子)", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "帽子を被って公園に行きます。", furigana: "ぼうしをかぶってこうえんにいきます。", en: "戴上帽子去公園。" }] },
  { id: "v_c_kakeru_glasses", word: "かける", furigana: "かける", romaji: "kakeru", meaning: "戴 (眼鏡)", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "彼は黒い眼鏡をかけています。", furigana: "かれはくろいめがねをかけています。", en: "他戴著黑框眼鏡。" }] },
  { id: "v_c_nugu", word: "脱ぐ", furigana: "ぬぐ", romaji: "nugu", meaning: "脫下", level: "N5", category: "fashion_beauty",
    sentences: [{ ja: "部屋に入る時は靴を脱いでください。", furigana: "へやにはいるときはくつをぬいでください。", en: "進房間時請脫鞋。" }] },
  { id: "v_c_hade", word: "派手", furigana: "はで", romaji: "hade", meaning: "花俏的 / 華麗的", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "彼女はいつも派手な服を着ています。", furigana: "かのじょはいつもはでなふくをきています。", en: "她總是穿著花俏的衣服。" }] },
  { id: "v_c_jimi", word: "地味", furigana: "じみ", romaji: "jimi", meaning: "樸素的", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "私の服は地味な色が多いです。", furigana: "わたしのふくはじみないろがおおいです。", en: "我的衣服大多是樸素的顏色。" }] },
  { id: "v_c_oshare", word: "おしゃれ", furigana: "おしゃれ", romaji: "oshare", meaning: "時尚的", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "彼はおしゃれな靴を履いています。", furigana: "かれはおしゃれなくつをはいています。", en: "他穿著時尚的鞋子。" }] },
  { id: "v_c_niau", word: "似合う", furigana: "にあう", romaji: "niau", meaning: "適合", level: "N3", category: "fashion_beauty",
    sentences: [{ ja: "その赤いドレス、とてもよく似合っていますよ。", furigana: "そのあかいどれす、とてもよくにあっていますよ。", en: "那件紅色的洋裝非常適合妳喔。" }] },

  // ================= 居住與家電 (housing_space) =================
  { id: "v_h_ie", word: "家", furigana: "いえ", romaji: "ie", meaning: "家 / 房子", level: "N5", category: "housing_space",
    sentences: [{ ja: "私の家は駅から近いです。", furigana: "わたしのいえはえきからちかいです。", en: "我的家離車站很近。" }] },
  { id: "v_h_heya", word: "部屋", furigana: "へや", romaji: "heya", meaning: "房間", level: "N5", category: "housing_space",
    sentences: [{ ja: "自分の部屋をきれいに掃除します。", furigana: "じぶんのへやをきれいにそうじします。", en: "把自己的房間打掃乾淨。" }] },
  { id: "v_h_manshon", word: "マンション", furigana: "まんしょん", romaji: "manshon", meaning: "公寓 (高級)", level: "N5", category: "housing_space",
    sentences: [{ ja: "高いマンションに住んでいます。", furigana: "たかいまんしょんにすんでいます。", en: "住在高層公寓裡。" }] },
  { id: "v_h_tatemono", word: "建物", furigana: "たてもの", romaji: "tatemono", meaning: "建築物", level: "N5", category: "housing_space",
    sentences: [{ ja: "あそこに白い建物が見えます。", furigana: "あそこにしろいたてものがみえます。", en: "在那裡看得到白色的建築物。" }] },
  { id: "v_h_kabe", word: "壁", furigana: "かべ", romaji: "kabe", meaning: "牆壁", level: "N4", category: "housing_space",
    sentences: [{ ja: "壁に絵を飾ります。", furigana: "かべにえをかざります。", en: "在牆上掛畫。" }] },
  { id: "v_h_yuka", word: "床", furigana: "ゆか", romaji: "yuka", meaning: "地板", level: "N3", category: "housing_space",
    sentences: [{ ja: "床に座ってテレビを見ます。", furigana: "ゆかにすわっててれびをみます。", en: "坐在地板上看電視。" }] },
  { id: "v_h_mado", word: "窓", furigana: "まど", romaji: "mado", meaning: "窗戶", level: "N5", category: "housing_space",
    sentences: [{ ja: "暑いので窓を開けてください。", furigana: "あついのでまどをあけてください。", en: "因為很熱，請打開窗戶。" }] },
  { id: "v_h_doa", word: "ドア", furigana: "どあ", romaji: "doa", meaning: "門", level: "N5", category: "housing_space",
    sentences: [{ ja: "ノックしてからドアを開けます。", furigana: "のっくしてからどあをあけます。", en: "敲門後再開門。" }] },
  { id: "v_h_kaidan", word: "階段", furigana: "かいだん", romaji: "kaidan", meaning: "樓梯", level: "N5", category: "housing_space",
    sentences: [{ ja: "階段を上って二階に行きます。", furigana: "かいだんをのぼってにかいにいきます。", en: "上樓梯去二樓。" }] },
  { id: "v_h_niwa", word: "庭", furigana: "にわ", romaji: "niwa", meaning: "庭院", level: "N5", category: "housing_space",
    sentences: [{ ja: "庭で花を育てています。", furigana: "にわではなをそだてています。", en: "在庭院裡種花。" }] },
  { id: "v_h_genkan", word: "玄関", furigana: "げんかん", romaji: "genkan", meaning: "玄關", level: "N5", category: "housing_space",
    sentences: [{ ja: "玄関で靴を脱ぎます。", furigana: "げんかんでくつをぬぎます。", en: "在玄關脫鞋。" }] },
  { id: "v_h_daidokoro", word: "台所", furigana: "だいどころ", romaji: "daidokoro", meaning: "廚房", level: "N5", category: "housing_space",
    sentences: [{ ja: "台所で晩ご飯を作ります。", furigana: "だいどころでばんごはんをつくります。", en: "在廚房做晚餐。" }] },
  { id: "v_h_ofuro", word: "お風呂", furigana: "おふろ", romaji: "ofuro", meaning: "浴室 / 澡盆", level: "N5", category: "housing_space",
    sentences: [{ ja: "毎日お風呂に入ります。", furigana: "まいにちおふろにはいります。", en: "每天洗澡。" }] },
  { id: "v_h_toire", word: "トイレ", furigana: "といれ", romaji: "toire", meaning: "廁所", level: "N5", category: "housing_space",
    sentences: [{ ja: "トイレはどこですか？", furigana: "といれはどこですか？", en: "廁所在哪裡？" }] },
  { id: "v_h_beddo", word: "ベッド", furigana: "べっど", romaji: "beddo", meaning: "床", level: "N5", category: "housing_space",
    sentences: [{ ja: "新しいベッドを買いました。", furigana: "あたらしいべっどをかいました。", en: "買了新床。" }] },
  { id: "v_h_futon", word: "布団", furigana: "ふとん", romaji: "futon", meaning: "棉被", level: "N4", category: "housing_space",
    sentences: [{ ja: "布団を敷いて寝ます。", furigana: "ふとんをしいてねます。", en: "鋪好棉被睡覺。" }] },
  { id: "v_h_tsukue", word: "机", furigana: "つくえ", romaji: "tsukue", meaning: "桌子 / 書桌", level: "N5", category: "housing_space",
    sentences: [{ ja: "机の上をきれいに片付けます。", furigana: "つくえのうえをきれいにかたづけます。", en: "把桌子上整理乾淨。" }] },
  { id: "v_h_teeburu", word: "テーブル", furigana: "てーぶる", romaji: "teeburu", meaning: "餐桌", level: "N5", category: "housing_space",
    sentences: [{ ja: "テーブルの上に料理を並べます。", furigana: "てーぶるのうえにりょうりをならべます。", en: "把料理擺在餐桌上。" }] },
  { id: "v_h_isu", word: "椅子", furigana: "いす", romaji: "isu", meaning: "椅子", level: "N5", category: "housing_space",
    sentences: [{ ja: "どうぞ、その椅子に座ってください。", furigana: "どうぞ、そのいすにすわってください。", en: "請坐在那張椅子上。" }] },
  { id: "v_h_sofaa", word: "ソファ", furigana: "そふぁ", romaji: "sofaa", meaning: "沙發", level: "N4", category: "housing_space",
    sentences: [{ ja: "ソファで横になって休みます。", furigana: "そふぁでよこになってやすみます。", en: "躺在沙發上休息。" }] },
  { id: "v_h_hondana", word: "本棚", furigana: "ほんだな", romaji: "hondana", meaning: "書架", level: "N5", category: "housing_space",
    sentences: [{ ja: "本棚にたくさんの本があります。", furigana: "ほんだなにたくさんのほんがあります。", en: "書架上有很多書。" }] },
  { id: "v_h_gomibako", word: "ゴミ箱", furigana: "ごみばこ", romaji: "gomibako", meaning: "垃圾桶", level: "N5", category: "housing_space",
    sentences: [{ ja: "ゴミはゴミ箱に捨ててください。", furigana: "ごみはごみばこにすててください。", en: "垃圾請丟進垃圾桶。" }] },
  { id: "v_h_terebi", word: "テレビ", furigana: "てれび", romaji: "terebi", meaning: "電視", level: "N5", category: "housing_space",
    sentences: [{ ja: "晩ご飯を食べながらテレビを見ます。", furigana: "ばんごはんをたべながらてれびをみます。", en: "邊吃晚餐邊看電視。" }] },
  { id: "v_h_reizouko", word: "冷蔵庫", furigana: "れいぞうこ", romaji: "reizouko", meaning: "冰箱", level: "N5", category: "housing_space",
    sentences: [{ ja: "牛乳を冷蔵庫に入れます。", furigana: "ぎゅうにゅうをれいぞうこにいれます。", en: "把牛奶放進冰箱。" }] },
  { id: "v_h_sentakuki", word: "洗濯機", furigana: "せんたくき", romaji: "sentakuki", meaning: "洗衣機", level: "N4", category: "housing_space",
    sentences: [{ ja: "洗濯機で服を洗います。", furigana: "せんたくきでふくをあらいます。", en: "用洗衣機洗衣服。" }] },
  { id: "v_h_soujiki", word: "掃除機", furigana: "そうじき", romaji: "soujiki", meaning: "吸塵器", level: "N4", category: "housing_space",
    sentences: [{ ja: "部屋に掃除機をかけます。", furigana: "へやにそうじきをかけます。", en: "用吸塵器打掃房間。" }] },
  { id: "v_h_denshirenji", word: "電子レンジ", furigana: "でんしれんじ", romaji: "denshirenji", meaning: "微波爐", level: "N4", category: "housing_space",
    sentences: [{ ja: "電子レンジで料理を温めます。", furigana: "でんしれんじでりょうりをあたためます。", en: "用微波爐加熱料理。" }] },
  { id: "v_h_eakon", word: "エアコン", furigana: "えあこん", romaji: "eakon", meaning: "冷暖氣機", level: "N4", category: "housing_space",
    sentences: [{ ja: "暑いのでエアコンをつけます。", furigana: "あついのでえあこんをつけます。", en: "因為很熱，打開冷氣。" }] },
  { id: "v_h_denki", word: "電気", furigana: "でんき", romaji: "denki", meaning: "電燈 / 電", level: "N5", category: "housing_space",
    sentences: [{ ja: "部屋が暗いので電気をつけます。", furigana: "へやがくらいのででんきをつけます。", en: "房間很暗所以開燈。" }] },
  { id: "v_h_sumu", word: "住む", furigana: "すむ", romaji: "sumu", meaning: "居住", level: "N5", category: "housing_space",
    sentences: [{ ja: "私は東京に住んでいます。", furigana: "わたしはとうきょうにすんでいます。", en: "我住在東京。" }] },
  { id: "v_h_hikkosu", word: "引っ越す", furigana: "ひっこす", romaji: "hikkosu", meaning: "搬家", level: "N4", category: "housing_space",
    sentences: [{ ja: "来月、新しいアパートに引っ越します。", furigana: "らいげつ、あたらしいあぱーとにひっこします。", en: "下個月搬到新的公寓。" }] },
  { id: "v_h_soujisuru", word: "掃除する", furigana: "そうじする", romaji: "soujisuru", meaning: "打掃", level: "N5", category: "housing_space",
    sentences: [{ ja: "週末は家を掃除します。", furigana: "しゅうまつはいえをそうじします。", en: "週末打掃家裡。" }] },
  { id: "v_h_sentakusuru", word: "洗濯する", furigana: "せんたくする", romaji: "sentakusuru", meaning: "洗衣服", level: "N5", category: "housing_space",
    sentences: [{ ja: "天気がいいのでたくさん洗濯します。", furigana: "てんきがいいのでたくさんせんたくします。", en: "天氣很好，所以洗很多衣服。" }] },
  { id: "v_h_katazukeru", word: "片付ける", furigana: "かたづける", romaji: "katazukeru", meaning: "整理", level: "N4", category: "housing_space",
    sentences: [{ ja: "テーブルの上を片付けます。", furigana: "てーぶるのうえをかたづけます。", en: "把桌上整理乾淨。" }] },
  { id: "v_h_suteru", word: "捨てる", furigana: "すてる", romaji: "suteru", meaning: "丟棄", level: "N4", category: "housing_space",
    sentences: [{ ja: "いらないものをゴミ箱に捨てます。", furigana: "いらないものをごみばこにすてます。", en: "把不需要的東西丟進垃圾桶。" }] },

  // ================= 交通與移動 (transport_mobility) =================
  { id: "v_t_jitensha", word: "自転車", furigana: "じてんしゃ", romaji: "jitensha", meaning: "腳踏車", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "自転車で学校へ行きます。", furigana: "じてんしゃでがっこうへいきます。", en: "騎腳踏車去學校。" }] },
  { id: "v_t_kuruma", word: "車", furigana: "くるま", romaji: "kuruma", meaning: "汽車", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "父が車を運転します。", furigana: "ちちがくるまをうんてんします。", en: "爸爸開車。" }] },
  { id: "v_t_takushii", word: "タクシー", furigana: "たくしー", romaji: "takushii", meaning: "計程車", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "駅からタクシーに乗ります。", furigana: "えきからたくしーにのります。", en: "從車站搭計程車。" }] },
  { id: "v_t_basu", word: "バス", furigana: "ばす", romaji: "basu", meaning: "公車", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "バスに乗って会社に行きます。", furigana: "ばすにのってかいしゃにいきます。", en: "搭公車去公司。" }] },
  { id: "v_t_densha", word: "電車", furigana: "でんしゃ", romaji: "densha", meaning: "電車", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "電車の中で本を読みます。", furigana: "でんしゃのなかでほんをよみます。", en: "在電車上看書。" }] },
  { id: "v_t_chikatetsu", word: "地下鉄", furigana: "ちかてつ", romaji: "chikatetsu", meaning: "地鐵", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "地下鉄は早くて便利です。", furigana: "ちかてつははやくてべんりです。", en: "地鐵又快又方便。" }] },
  { id: "v_t_shinkansen", word: "新幹線", furigana: "しんかんせん", romaji: "shinkansen", meaning: "新幹線", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "新幹線で京都へ行きます。", furigana: "しんかんせんできょうとへいきます。", en: "搭新幹線去京都。" }] },
  { id: "v_t_hikouki", word: "飛行機", furigana: "ひこうき", romaji: "hikouki", meaning: "飛機", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "飛行機に乗って海外へ行きます。", furigana: "ひこうきにのってかいがいへいきます。", en: "搭飛機出國。" }] },
  { id: "v_t_fune", word: "船", furigana: "ふね", romaji: "fune", meaning: "船", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "船から海を眺めます。", furigana: "ふねからうみをながめます。", en: "從船上眺望大海。" }] },
  { id: "v_t_eki", word: "駅", furigana: "えき", romaji: "eki", meaning: "車站", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "駅の近くで友達と待ち合わせます。", furigana: "えきのちかくでともだちとまちあわせます。", en: "在車站附近和朋友碰面。" }] },
  { id: "v_t_basutei", word: "バス停", furigana: "ばすてい", romaji: "basutei", meaning: "公車站", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "バス停でバスを待ちます。", furigana: "ばすていでばすをまちます。", en: "在公車站等公車。" }] },
  { id: "v_t_kuukou", word: "空港", furigana: "くうこう", romaji: "kuukou", meaning: "機場", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "明日、空港に友達を迎えに行きます。", furigana: "あした、くうこうにともだちをむかえにいきます。", en: "明天去機場接朋友。" }] },
  { id: "v_t_kousaten", word: "交差点", furigana: "こうさてん", romaji: "kousaten", meaning: "十字路口", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "交差点を右に曲がります。", furigana: "こうさてんをみぎにまがります。", en: "在十字路口右轉。" }] },
  { id: "v_t_shingou", word: "信号", furigana: "しんごう", romaji: "shingou", meaning: "紅綠燈", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "信号が赤になったら止まります。", furigana: "しんごうがあかになったらとまります。", en: "紅綠燈變紅燈就要停下來。" }] },
  { id: "v_t_michi", word: "道", furigana: "みち", romaji: "michi", meaning: "道路", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "この道をまっすぐ行くと駅に着きます。", furigana: "このみちをまっすぐいくとえきにつきます。", en: "沿著這條路直走就會到車站。" }] },
  { id: "v_t_migi", word: "右", furigana: "みぎ", romaji: "migi", meaning: "右邊", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "次の角を右に曲がってください。", furigana: "つぎのかどをみぎにまがってください。", en: "請在下一個轉角右轉。" }] },
  { id: "v_t_hidari", word: "左", furigana: "ひだり", romaji: "hidari", meaning: "左邊", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "左を見ると、富士山が見えます。", furigana: "ひだりをみると、ふじさんがみえます。", en: "往左看就可以看到富士山。" }] },
  { id: "v_t_mae", word: "前", furigana: "まえ", romaji: "mae", meaning: "前面", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "駅の前に大きなビルがあります。", furigana: "えきのまえにおおきなびるがあります。", en: "車站前面有一棟大樓。" }] },
  { id: "v_t_ushiro", word: "後ろ", furigana: "うしろ", romaji: "ushiro", meaning: "後面", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "私の後ろに並んでください。", furigana: "わたしのうしろにならんでください。", en: "請排在我後面。" }] },
  { id: "v_t_massugu", word: "まっすぐ", furigana: "まっすぐ", romaji: "massugu", meaning: "筆直 / 直走", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "この道をまっすぐ進んでください。", furigana: "このみちをまっすぐすすんでください。", en: "請直直往前走。" }] },
  { id: "v_t_noru", word: "乗る", furigana: "のる", romaji: "noru", meaning: "搭乘", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "東京駅から電車に乗ります。", furigana: "とうきょうえきからでんしゃにのります。", en: "從東京車站搭電車。" }] },
  { id: "v_t_oriru", word: "降りる", furigana: "おりる", romaji: "oriru", meaning: "下車", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "次の駅で降ります。", furigana: "つぎのえきでおります。", en: "在下一站下車。" }] },
  { id: "v_t_norikaeru", word: "乗り換える", furigana: "のりかえる", romaji: "norikaeru", meaning: "轉車", level: "N4", category: "transport_mobility",
    sentences: [{ ja: "新宿駅で地下鉄に乗り換えます。", furigana: "しんじゅくえきでちかてつにのりかえます。", en: "在新宿車站換乘地鐵。" }] },
  { id: "v_t_kippu", word: "切符", furigana: "きっぷ", romaji: "kippu", meaning: "車票", level: "N5", category: "transport_mobility",
    sentences: [{ ja: "機械で切符を買います。", furigana: "きかいできっぷをかいます。", en: "用機器買車票。" }] },

  // ================= 休閒育樂與購物 (leisure_sports) =================
  { id: "v_l_kaimono", word: "買い物", furigana: "かいもの", romaji: "kaimono", meaning: "購物 / 買東西", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "週末はデパートへ買い物に行きます。", furigana: "しゅうまつはでぱーとへかいものにいきます。", en: "週末去百貨公司買東西。" }] },
  { id: "v_l_okane", word: "お金", furigana: "おかね", romaji: "okane", meaning: "錢", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "お金が足りないので買えません。", furigana: "おかねがたりないのでかえません。", en: "錢不夠所以不能買。" }] },
  { id: "v_l_genkin", word: "現金", furigana: "げんきん", romaji: "genkin", meaning: "現金", level: "N3", category: "leisure_sports",
    sentences: [{ ja: "支払いは現金でお願いします。", furigana: "しはらいはげんきんとおねがいします。", en: "請用現金支付。" }] },
  { id: "v_l_kurejittokaado", word: "クレジットカード", furigana: "くれじっとかーど", romaji: "kurejittokaado", meaning: "信用卡", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "クレジットカードは使えますか？", furigana: "くれじっとかーどはつかえますか？", en: "可以使用信用卡嗎？" }] },
  { id: "v_l_otsuri", word: "お釣り", furigana: "おつり", romaji: "otsuri", meaning: "找零", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "お釣りをもらい忘れました。", furigana: "おつりをもらいわすれました。", en: "忘記拿找的零錢了。" }] },
  { id: "v_l_yasui", word: "安い", furigana: "やすい", romaji: "yasui", meaning: "便宜的", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "このスーパーは野菜が安いです。", furigana: "このすーぱーはやさいがやすいです。", en: "這家超市的蔬菜很便宜。" }] },
  { id: "v_l_takai", word: "高い", furigana: "たかい", romaji: "takai", meaning: "昂貴的 / 高的", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "このカバンはとても高いです。", furigana: "このかばんはとてもたかいです。", en: "這個包包非常貴。" }] },
  { id: "v_l_shumi", word: "趣味", furigana: "しゅみ", romaji: "shumi", meaning: "興趣", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "私の趣味は写真を撮ることです。", furigana: "わたしのしゅみはしゃしんをとることです。", en: "我的興趣是拍照。" }] },
  { id: "v_l_eiga", word: "映画", furigana: "えいが", romaji: "eiga", meaning: "電影", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "友達と一緒に映画を見ます。", furigana: "ともだちといっしょにえいがをみます。", en: "和朋友一起看電影。" }] },
  { id: "v_l_ongaku", word: "音楽", furigana: "おんがく", romaji: "ongaku", meaning: "音樂", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "音楽を聴きながら散歩します。", furigana: "おんがくをききながらさんぽします。", en: "邊聽音樂邊散步。" }] },
  { id: "v_l_dokusho", word: "読書", furigana: "どくしょ", romaji: "dokusho", meaning: "閱讀", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "秋は読書の季節です。", furigana: "あきはどくしょのきせつです。", en: "秋天是閱讀的季節。" }] },
  { id: "v_l_supootsu", word: "スポーツ", furigana: "すぽーつ", romaji: "supootsu", meaning: "運動", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "スポーツをして汗をかきます。", furigana: "すぽーつをしてあせをかきます。", en: "做運動流汗。" }] },
  { id: "v_l_yakyuu", word: "野球", furigana: "やきゅう", romaji: "yakyuu", meaning: "棒球", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "テレビで野球の試合を見ます。", furigana: "てれびでやきゅうのしあいをみます。", en: "在電視上看棒球比賽。" }] },
  { id: "v_l_sakkaa", word: "サッカー", furigana: "さっかー", romaji: "sakkaa", meaning: "足球", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "公園で子供たちがサッカーをしています。", furigana: "こうえんでこどもたちがさっかーをしています。", en: "孩子們在公園踢足球。" }] },
  { id: "v_l_oyogu", word: "泳ぐ", furigana: "およぐ", romaji: "oyogu", meaning: "游泳", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "プールで１時間泳ぎました。", furigana: "ぷーるでいちじかんおよぎました。", en: "在游泳池游了一個小時。" }] },
  { id: "v_l_hashiru", word: "走る", furigana: "はしる", romaji: "hashiru", meaning: "跑", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "健康のために毎日走っています。", furigana: "けんこうのためにまいにちはしっています。", en: "為了健康每天跑步。" }] },
  { id: "v_l_ryokou", word: "旅行", furigana: "りょこう", romaji: "ryokou", meaning: "旅行", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "来月、家族で旅行に行きます。", furigana: "らいげつ、かぞくでりょこうにいきます。", en: "下個月和家人去旅行。" }] },
  { id: "v_l_kankou", word: "観光", furigana: "かんこう", romaji: "kankou", meaning: "觀光", level: "N3", category: "leisure_sports",
    sentences: [{ ja: "京都でいろいろな観光地を回りました。", furigana: "きょうとでいろいろなかんこうちをまわりました。", en: "在京都逛了許多觀光景點。" }] },
  { id: "v_l_omiyage", word: "お土産", furigana: "おみやげ", romaji: "omiyage", meaning: "伴手禮 / 紀念品", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "旅行のお土産にクッキーを買いました。", furigana: "りょこうのおみやげにくっきーをかいました。", en: "買了餅乾當作旅行的伴手禮。" }] },
  { id: "v_l_hoteru", word: "ホテル", furigana: "ほてる", romaji: "hoteru", meaning: "飯店", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "海の近くのホテルに泊まります。", furigana: "うみのちかくのほてるにとまります。", en: "住在海邊的飯店。" }] },
  { id: "v_l_onsen", word: "温泉", furigana: "おんせん", romaji: "onsen", meaning: "溫泉", level: "N4", category: "leisure_sports",
    sentences: [{ ja: "冬は温泉に入るのが一番です。", furigana: "ふゆはおんせんにはいるのがいちばんです。", en: "冬天泡溫泉是最棒的。" }] },
  { id: "v_l_nimotsu", word: "荷物", furigana: "にもつ", romaji: "nimotsu", meaning: "行李 / 物品", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "荷物が重いのでタクシーに乗ります。", furigana: "にもつがおもいのでたくしーにのります。", en: "因為行李很重所以搭計程車。" }] },
  { id: "v_l_pasupooto", word: "パスポート", furigana: "ぱすぽーと", romaji: "pasupooto", meaning: "護照", level: "N5", category: "leisure_sports",
    sentences: [{ ja: "海外に行く時はパスポートが必要です。", furigana: "かいがいにいくときはぱすぽーとがひつようです。", en: "出國時需要護照。" }] }
];

const n5Content = fs.readFileSync(n5File, 'utf8');
const sandbox = { window: {} };
vm.createContext(sandbox);
vm.runInContext(n5Content, sandbox);
const db = sandbox.window.JLPT_DATA_CHUNKS["N5"];

// Avoid duplicates
const existingWords = new Set(db.vocabulary.map(v => v.word));
const newWords = megaWords.filter(v => !existingWords.has(v.word));

db.vocabulary = db.vocabulary.concat(newWords);

const outputCode = "window.JLPT_DATA_CHUNKS = window.JLPT_DATA_CHUNKS || {};\n" +
"window.JLPT_DATA_CHUNKS[\"N5\"] = " + JSON.stringify(db, null, 2) + ";\n" +
"if (typeof module !== 'undefined') { module.exports = window.JLPT_DATA_CHUNKS[\"N5\"]; }\n";

fs.writeFileSync(n5File, outputCode, 'utf8');
console.log('Appended', newWords.length, 'Mega material life words to data_n5.js!');
